#!/usr/bin/env python3
from pathlib import Path
import json,catboost as cb,numpy as np,pandas as pd
HERE=Path(__file__).resolve().parent;ROOT=HERE if (HERE/'model').exists() else HERE.parent;B=ROOT/'model/COMBO-FK2-006'
BASE=["season","game_month","game_dayofweek","inning","top_bottom","game_type","balls_before","strikes_before","outs_before","run_top_before","run_bot_before","run_total_before","score_diff_home","score_diff_pitcher_team","runner_on_1b","runner_on_2b","runner_on_3b","num_runners_on","base_state","home_win_expectancy","away_win_expectancy","li","pitcher_id","batter_id","pitcher_hand","batter_hand","pitcher_team_id","batter_team_id","asof_pitcher_n","asof_pitcher_success_rate","asof_pitcher_reverse_rate","asof_pitcher_middle_rate","asof_pitcher_ball_rate","asof_pitcher_strike_rate","asof_pitcher_prev1_game_success_rate","asof_pitcher_prev3_game_success_rate","asof_pitcher_prev5_game_success_rate","asof_pitcher_prev1_game_middle_rate","asof_pitcher_prev3_game_middle_rate","asof_pitcher_prev5_game_middle_rate","asof_batter_n","asof_batter_success_rate","asof_batter_middle_rate","asof_pitcher_pitchmix_n","asof_pitcher_fastball_rate","asof_pitcher_breaking_rate","asof_pitcher_offspeed_rate"]
STATE=['cur_succ','cur_mid','cur_ball','cur_rev','cur_str','cur_bsucc','cur_bmid','cur_logn_pitch','cur_logn_mix','cur_logn_bat'];EX=[f'x_{r}_{c}' for r in ('cur_succ','cur_mid') for c in ('adv','onb','sh','bs')]+[f'h1_{r}_{c}' for r in ('cur_ball','cur_rev','cur_str') for c in ('sh','bs')];FK2=[f'f_{r}{w}' for r in ('succ','mid') for w in (1,3,5)]+[f'k2_{r}_{w}' for r in ('ball','rev') for w in ('two_strike','two_strike_low')];NEW=[];COLS=BASE+STATE+EX+FK2+['target_hist_pitcher_count_n','target_hist_pitcher_count_delta']
def main():
 t=pd.read_csv(ROOT/'data/test.csv',encoding='utf-8-sig');o=t.copy();pp=pd.read_csv(B/'asof_pitcher_id_prior.csv');bp=pd.read_csv(B/'asof_batter_id_prior.csv');mp=pd.read_csv(B/'asof_pitchmix_prior.csv');o=o.merge(pp,on='pitcher_id',how='left',validate='many_to_one').merge(bp,on='batter_id',how='left',validate='many_to_one').merge(mp,on='pitcher_id',how='left',validate='many_to_one');curp=(o.asof_pitcher_n.fillna(0)-o.prior_n_x.fillna(0)).clip(lower=0);curb=(o.asof_batter_n.fillna(0)-o.prior_n_y.fillna(0)).clip(lower=0);o['cur_logn_pitch']=np.log1p(curp);o['cur_logn_bat']=np.log1p(curb);o['cur_logn_mix']=np.log1p((o.asof_pitcher_pitchmix_n.fillna(0)-o.prior_pitchmix_n.fillna(0)).clip(lower=0));spec=[('asof_pitcher_success_rate','cur_succ','prior_asof_pitcher_success_rate',curp,o.asof_pitcher_n),('asof_pitcher_middle_rate','cur_mid','prior_asof_pitcher_middle_rate',curp,o.asof_pitcher_n),('asof_pitcher_ball_rate','cur_ball','prior_asof_pitcher_ball_rate',curp,o.asof_pitcher_n),('asof_pitcher_reverse_rate','cur_rev','prior_asof_pitcher_reverse_rate',curp,o.asof_pitcher_n),('asof_pitcher_strike_rate','cur_str','prior_asof_pitcher_strike_rate',curp,o.asof_pitcher_n),('asof_batter_success_rate','cur_bsucc','prior_asof_batter_success_rate',curb,o.asof_batter_n),('asof_batter_middle_rate','cur_bmid','prior_asof_batter_middle_rate',curb,o.asof_batter_n)]
 for rc,lb,pc,cur,n in spec:o[lb]=((n.fillna(0)*o[rc].fillna(0)-o[pc].fillna(0))/cur).where(cur>0)
 o['adv']=(o.strikes_before>o.balls_before).astype(float);o['onb']=(o.num_runners_on>0).astype(float);o['sh']=(o.pitcher_hand.astype(str)==o.batter_hand.astype(str)).astype(float);o['bs']=o.balls_before-o.strikes_before;full=(o.balls_before==3)&(o.strikes_before==2);pa=((o.balls_before==0)&o.strikes_before.isin([1,2]))|((o.balls_before==1)&(o.strikes_before==2));ba=((o.balls_before==2)&(o.strikes_before==0))|((o.balls_before==3)&o.strikes_before.isin([0,1]));o['count_state']=np.select([full,pa,ba],['full_count','ahead_pitcher','ahead_batter'],default='neutral')
 for f in EX:z=f.split('_');o[f]=o['_'.join(z[1:3])]*o[z[3]]
 lk=pd.read_csv(B/'pitcher_count_lookup.csv');o=o.merge(lk,on=['pitcher_id','count_state'],how='left',validate='many_to_one');o[['target_hist_pitcher_count_n','target_hist_pitcher_count_delta']]=o[['target_hist_pitcher_count_n','target_hist_pitcher_count_delta']].fillna(0)
 c=pd.read_csv(B/'trackman_count_lookup.csv');h=pd.read_csv(B/'trackman_hand_lookup.csv').rename(columns={'batter_hand':'__hand'});o=o.merge(c,on=['pitcher_id','balls_before','strikes_before'],how='left',validate='many_to_one');o['__hand']=o['batter_hand'].map({1:'Left',2:'Right'}).fillna(o['batter_hand'].astype(str));o=o.merge(h,on=['pitcher_id','__hand'],how='left',validate='many_to_one').drop(columns='__hand');
 for r in ('succ','mid'):
  cur=o[f'cur_{r}']
  for w in (1,3,5): o[f'f_{r}{w}']=o[f'asof_pitcher_prev{w}_game_{"success" if r=="succ" else "middle"}_rate']-cur
 two=(o.strikes_before==2); low=two & (o.balls_before<=1)
 for r in ('ball','rev'):
  o[f'k2_{r}_two_strike']=o[f'cur_{r}']*two.astype(float);o[f'k2_{r}_two_strike_low']=o[f'cur_{r}']*low.astype(float)
 x=o[COLS].copy();model=cb.CatBoostClassifier();model.load_model(B/'model.cbm');cats=[COLS[i] for i in model.get_cat_feature_indices()]
 for col in cats:x[col]=x[col].astype(str)
 p=model.predict_proba(cb.Pool(x,cat_features=cats,feature_names=COLS))[:,1];r=pd.DataFrame({'row_id':t.row_id,'control_success':p});(B/'isolated_submission.csv').write_text(r.to_csv(index=False));(ROOT/'output').mkdir(exist_ok=True);r.to_csv(ROOT/'output/submission.csv',index=False);assert list(x.columns)==COLS and np.isfinite(p).all() and ((p>=0)&(p<=1)).all();print(json.dumps({'rows':len(r),'features':len(x.columns),'min':float(p.min()),'max':float(p.max()),'status':'PASS_ISOLATED_INFERENCE','submission_status':'HOLD'},ensure_ascii=False))
if __name__=='__main__':main()
