#!/usr/bin/env python3
import hashlib,importlib.util,json,pickle
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'model/REF4-F-GATED-PSYCH-LATENT-PRODUCTION-044A';CONDS=('high_li','extreme_li','traffic','risp','late','close','behind','three_ball','two_strike','full_count','compound_pressure')
spec=importlib.util.spec_from_file_location('feature_runner',ROOT/'scripts/run_ref4_trainonly_psych_latent_042a.py');fr=importlib.util.module_from_spec(spec);spec.loader.exec_module(fr)
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def profile_bundle(history,alpha):
 h=history.reset_index(drop=True);cond=fr.conditions(h);y=h.control_success.astype(float);pitch=h.pitcher_id.astype(str);g=float(y.mean());overall=h.assign(_y=y).groupby(pitch,sort=False)._y.agg(['sum','count']);rate=(overall['sum']+alpha*g)/(overall['count']+alpha);out=pd.DataFrame(index=overall.index);out['psych_history_log_n']=np.log1p(overall['count']);league={}
 for name in CONDS:
  mask=cond[name].astype(bool);ctx=float(y[mask].mean()) if mask.any() else g;league[name]=ctx-g;agg=h.loc[mask].assign(_y=y[mask]).groupby(pitch[mask],sort=False)._y.agg(['sum','count']);s=agg['sum'].reindex(out.index).fillna(0);n=agg['count'].reindex(out.index).fillna(0);r=(s+alpha*rate)/(n+alpha);out['psych_'+name+'_effect']=r-rate;out['psych_'+name+'_reliability']=n/(n+alpha)
 return {'profile':out.reset_index(names='pitcher_id'),'league':league}
def main():
 c=json.loads((OUT/'audit_contract.json').read_text());pre=json.loads((OUT/'preflight_report.json').read_text());assert pre['status']=='AUDIT_VERIFIED' and pre['fail_count']==0;cfg=c['fixed_fit'];raw=pd.read_csv(ROOT/'data/train.csv',low_memory=False);tm=pd.read_csv(ROOT/'data/trackman_history.csv',usecols=['pitcher_trackman_id','season','balls_before','strikes_before','batter_hand','pitch_type_group']);byid=raw.set_index('row_id',drop=False);xs=[];ys=[];weights=[];source=[]
 for key in ('2022','2023','2024'):
  year=int(key);o=pd.read_csv(ROOT/c['oof_sources'][key]);rows=byid.loc[o.row_id].reset_index(drop=True);mp=pd.read_csv(ROOT/c['fold_mapping'][key]);tab=fr.latent_table(year,mp,tm,float(cfg['latent_parent_strength']),float(cfg['latent_context_strength']));x=pd.concat([fr.psych(rows,raw.loc[raw.season.lt(year)],float(cfg['psych_shrinkage_alpha'])),fr.latent(rows,tab)],axis=1);xs.append(x);ys.append(o.target.to_numpy(float)-o.prediction.to_numpy(float));weights.append(np.full(len(o),float(cfg['season_weights'][key])));source.append({'season':year,'rows':len(o),'feature_count':len(x.columns),'mapping_rows':len(mp),'latent_rows':len(tab),'history_max_season':year-1,'trackman_max_season':int(tm.loc[tm.season.lt(year),'season'].max())})
 x=pd.concat(xs,ignore_index=True);target=np.concatenate(ys);w=np.concatenate(weights);mean=x.mean();std=x.std().replace(0,1).fillna(1);z=((x-mean)/std).fillna(0);model=Ridge(alpha=float(cfg['ridge_alpha']),fit_intercept=False).fit(z,target,sample_weight=w);np.savez_compressed(OUT/'psych_latent_meta.npz',columns=np.array(x.columns,dtype='U'),mean=mean.to_numpy(),std=std.to_numpy(),coef=model.coef_,scale=float(cfg['correction_scale']),ridge_alpha=float(cfg['ridge_alpha']),fit_seasons=np.array(cfg['fit_seasons']),season_weights=np.array([cfg['season_weights'][str(y)] for y in cfg['fit_seasons']]))
 bundle=profile_bundle(raw,float(cfg['psych_shrinkage_alpha']));
 with open(OUT/'psych_profile.pkl','wb') as f:pickle.dump(bundle,f,protocol=4)
 prodmap=pd.read_csv(ROOT/c['production_mapping']);latent=fr.latent_table(2025,prodmap,tm,float(cfg['latent_parent_strength']),float(cfg['latent_context_strength']));latent.insert(1,'season',2025);latent.to_csv(OUT/'latent_pitch_context.csv',index=False)
 pf=pd.concat([raw.loc[raw.game_type.eq('F')].tail(128),raw.loc[raw.game_type.ne('F')].tail(128)],ignore_index=True);pf['season']=2025;px=pd.concat([fr.psych(pf,raw,float(cfg['psych_shrinkage_alpha'])),fr.latent(pf,latent.drop(columns='season'))],axis=1);cor=((px[x.columns]-mean)/std).fillna(0).to_numpy()@model.coef_*float(cfg['correction_scale']);probe=pd.DataFrame({'row_id':pf.row_id,'game_type':pf.game_type,'correction':cor,'gated_correction':np.where(pf.game_type.eq('F'),cor,0.0)});probe.to_csv(OUT/'production_probe.csv',index=False)
 fit={'experiment_id':c['experiment_id'],'status':'PENDING_AUDIT','fit_rows':len(x),'fit_seasons':cfg['fit_seasons'],'season_rows':{str(y):int((raw.season==y).sum()) for y in cfg['fit_seasons']},'feature_count':len(x.columns),'feature_names':x.columns.tolist(),'ridge_coefficient_count':len(model.coef_),'ridge_coefficient_min':float(model.coef_.min()),'ridge_coefficient_max':float(model.coef_.max()),'profile_rows':len(bundle['profile']),'latent_rows':len(latent),'latent_source_max_season':int(tm.season.max()),'production_mapping_rows':len(prodmap),'probe_rows':len(probe),'probe_F_rows':int(probe.game_type.eq('F').sum()),'source_folds':source,'training_performed':True,'test_read':False,'test_inference_performed':False,'candidate_bundle_created':False,'zip_created':False};(OUT/'production_fit.json').write_text(json.dumps(fit,ensure_ascii=False,indent=2)+'\n');(OUT/'result.json').write_text(json.dumps(fit,ensure_ascii=False,indent=2)+'\n');(OUT/'result.md').write_text(f"# {c['experiment_id']}\n\n- status: `PENDING_AUDIT`\n- fit rows: `{len(x)}`\n- features: `{len(x.columns)}`\n- profile rows: `{len(bundle['profile'])}`\n- latent rows: `{len(latent)}`\n- test read: `false`\n- ZIP: `false`\n")
 paths=[OUT/'audit_contract.json',OUT/'preflight_report.json',OUT/'preflight_report.md',OUT/'psych_profile.pkl',OUT/'latent_pitch_context.csv',OUT/'psych_latent_meta.npz',OUT/'production_probe.csv',OUT/'production_fit.json',OUT/'result.json',OUT/'result.md',ROOT/'data/train.csv',ROOT/'data/trackman_history.csv',ROOT/c['promotion_attestation'],ROOT/c['source_contract'],ROOT/c['production_mapping'],ROOT/'01_제약과금지사항.md',ROOT/'start04_uptostage.md',ROOT/c['preserve_zip'],ROOT/'scripts/preflight_ref4_f_gated_production_044a.py',ROOT/'scripts/run_ref4_f_gated_production_044a.py',ROOT/'scripts/verify_ref4_f_gated_production_044a.py',ROOT/'scripts/run_ref4_trainonly_psych_latent_042a.py',ROOT/'scripts/verify_ref4_trainonly_psych_latent_042a.py']+[ROOT/p for p in c['oof_sources'].values()]+[ROOT/p for p in c['fold_mapping'].values()];arts={str(p.relative_to(ROOT)):{'sha256':sha(p),'size':p.stat().st_size} for p in paths};(OUT/'audit_manifest.json').write_text(json.dumps({'experiment_id':c['experiment_id'],'status':'PENDING_VALIDATION','artifact_count':len(arts),'artifacts':arts,'asset_count':len(c['required_assets']),'fit_rows':len(x),'feature_count':len(x.columns),'probe_rows':len(probe)},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'status':'PENDING_AUDIT','fit_rows':len(x),'feature_count':len(x.columns),'profile_rows':len(bundle['profile']),'latent_rows':len(latent),'probe_rows':len(probe),'test_read':False,'zip_created':False},indent=2))
if __name__=='__main__':main()
