#!/usr/bin/env python3
import hashlib,json,sys,time
from pathlib import Path
import numpy as np,pandas as pd
from sklearn.linear_model import Ridge
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT));OUT=ROOT/'model/REF4-TRAINONLY-R-SPECIFIC-SPLIT-051A'
from src.entity_context_split import build_split_features
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def metric(y,p):
 b=float(np.mean((p-y)**2));ref=float(np.mean((y-y.mean())**2));q=1-b/ref;return {'rows':len(y),'target_rate':float(y.mean()),'brier':b,'bss':q,'local_score':1e5*q}
def boot(y,b,p,g,reps,seed):
 d=(b-y)**2-(p-y)**2;codes,u=pd.factorize(g,sort=True);s=np.bincount(codes,weights=d,minlength=len(u));n=np.bincount(codes,minlength=len(u));rng=np.random.default_rng(seed);v=np.empty(reps)
 for i in range(reps):q=rng.integers(0,len(u),len(u));v[i]=s[q].sum()/n[q].sum()
 return {'clusters':len(u),'repetitions':reps,'seed':seed,'brier_gain':float(d.mean()),'ci_low':float(np.quantile(v,.025)),'ci_high':float(np.quantile(v,.975))}
def main():
 started=time.time();c=json.loads((OUT/'audit_contract.json').read_text());pre=json.loads((OUT/'preflight_report.json').read_text());assert pre['status']=='AUDIT_VERIFIED' and pre['fail_count']==0;cols=['row_id','season','game_type','control_success','pitcher_id','batter_id','pitcher_hand','batter_hand','balls_before','strikes_before','inning','base_state'];raw=pd.read_csv(ROOT/c['official_train'],usecols=cols);oof={int(y):pd.read_csv(ROOT/p) for y,p in c['base_oof'].items()};f=pd.read_csv(ROOT/c['f_psych_predictions']);comp=pd.read_csv(ROOT/c['comparison_predictions']);features={};rows={};shrink=tuple(c['shrinkage_grid'])
 for year in (2022,2023,2024):rows[year]=oof[year][['row_id']].merge(raw,on='row_id',validate='one_to_one');features[year]=build_split_features(raw.loc[raw.season<year],rows[year],shrink);print('features',year,features[year].shape,flush=True)
 parts=[];folds={}
 for valid,fit_years in ((2023,(2022,)),(2024,(2022,2023))):
  fit_x=[];fit_y=[];fit_w=[]
  for year in fit_years:
   mask=oof[year].game_type.eq('R').to_numpy();fit_x.append(features[year].loc[mask]);fit_y.append(oof[year].target.to_numpy(float)[mask]-oof[year].prediction.to_numpy(float)[mask]);fit_w.append(np.full(mask.sum(),.55 if valid==2024 and year==2022 else 1.0))
  x=pd.concat(fit_x,ignore_index=True);yfit=np.concatenate(fit_y);w=np.concatenate(fit_w);mean=x.mean().to_numpy(float);std=x.std().replace(0,1).fillna(1).to_numpy(float);m=Ridge(alpha=float(c['ridge_alpha']),fit_intercept=False).fit(np.nan_to_num((x.to_numpy(float)-mean)/std),yfit,sample_weight=w);corr=m.predict(np.nan_to_num((features[valid].to_numpy(float)-mean)/std));base=oof[valid].prediction.to_numpy(float);target=oof[valid].target.to_numpy(float);r=oof[valid].game_type.eq('R').to_numpy();fpart=f.loc[f.season.eq(valid),'gated_prediction'].to_numpy(float);cand=np.where(r,np.clip(base+corr,1e-6,1-1e-6),fpart);bm=metric(target,base);cm=metric(target,cand);ci=boot(target,base,cand,oof[valid].pitcher_id.to_numpy(),int(c['promotion_gate']['cluster_bootstrap_repetitions']),int(c['promotion_gate']['cluster_bootstrap_seed_'+str(valid)]));folds[str(valid)]={'fit_seasons':list(fit_years),'fit_R_rows':len(x),'valid_R_rows':int(r.sum()),'valid_F_rows':int((~r).sum()),'feature_count':x.shape[1],'standardization_mean':mean.tolist(),'standardization_std':std.tolist(),'ridge_coef':m.coef_.tolist(),'baseline':bm,'candidate':cm,'brier_gain':bm['brier']-cm['brier'],'bss_gain':cm['bss']-bm['bss'],'cluster_ci':ci};parts.append(pd.DataFrame({'row_id':oof[valid].row_id,'season':valid,'pitcher_id':oof[valid].pitcher_id,'game_type':oof[valid].game_type,'target':target,'baseline_prediction':base,'r_specific_correction':corr,'candidate_prediction':cand}));print('fold',valid,folds[str(valid)]['brier_gain'],flush=True)
 d=pd.concat(parts,ignore_index=True);target=d.target.to_numpy(float);base=d.baseline_prediction.to_numpy(float);cand=d.candidate_prediction.to_numpy(float);pb=metric(target,base);pc=metric(target,cand);pg=pb['brier']-pc['brier'];comparison=comp.combined_prediction.to_numpy(float);comparison_brier=float(np.mean((comparison-target)**2));incremental=comparison_brier-pc['brier'];g={'2023_brier_gain_positive':folds['2023']['brier_gain']>0,'2024_brier_gain_positive':folds['2024']['brier_gain']>0,'pooled_brier_gain_positive':pg>0,'worst_season_bss_gain_positive':min(folds[k]['bss_gain'] for k in ('2023','2024'))>0,'2023_cluster_ci_low_positive':folds['2023']['cluster_ci']['ci_low']>0,'2024_cluster_ci_low_positive':folds['2024']['cluster_ci']['ci_low']>0,'pooled_gain_vs_048_positive':incremental>0};promotion=all(g.values());result={'experiment_id':c['experiment_id'],'candidate_name':'R_specific_split_plus_fixed_F_psych','candidate_status':'PENDING_AUDIT_PASS' if promotion else 'PENDING_AUDIT_FAIL','folds':folds,'pooled':{'baseline':pb,'candidate':pc,'brier_gain':pg,'comparison_048_brier':comparison_brier,'brier_gain_vs_048':incremental},'gate_checks':g,'gate_checks_count':len(g),'promotion_pass':promotion,'actual_leaf_count':1,'training_performed':True,'test_read':False,'test_inference_performed':False,'production_assets_created':False,'candidate_bundle_created':False,'zip_created':False,'elapsed_seconds':time.time()-started};d.to_csv(OUT/'oof_predictions.csv',index=False);(OUT/'result.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');(OUT/'result.md').write_text(f"# {c['experiment_id']}\n\n- status: `{result['candidate_status']}`\n- promotion pass: `{str(promotion).lower()}`\n- pooled gain: `{pg:.17g}`\n- gain vs 048: `{incremental:.17g}`\n");paths=[OUT/'audit_contract.json',OUT/'preflight_report.json',OUT/'preflight_report.md',OUT/'result.json',OUT/'result.md',OUT/'oof_predictions.csv',ROOT/c['official_train'],ROOT/c['f_psych_predictions'],ROOT/c['f_psych_attestation'],ROOT/c['comparison_predictions'],ROOT/c['comparison_attestation'],ROOT/c['preserve_zip'],ROOT/'01_제약과금지사항.md',ROOT/'src/entity_context_split.py',ROOT/'scripts/preflight_ref4_r_specific_split_051a.py',ROOT/'scripts/run_ref4_r_specific_split_051a.py',ROOT/'scripts/verify_ref4_r_specific_split_051a.py']+[ROOT/p for p in c['base_oof'].values()];arts={str(p.relative_to(ROOT)):{'sha256':sha(p),'size':p.stat().st_size} for p in paths};(OUT/'audit_manifest.json').write_text(json.dumps({'experiment_id':c['experiment_id'],'status':'PENDING_VALIDATION','artifact_count':len(arts),'artifacts':arts,'leaf_count':1,'gate_count':len(g),'oof_rows':len(d),'feature_count':40},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'candidate_status':result['candidate_status'],'promotion_pass':promotion,'gates':g,'pooled_brier_gain':pg,'gain_vs_048':incremental},indent=2))
if __name__=='__main__':main()
