#!/usr/bin/env python3
from __future__ import annotations
import hashlib,importlib.util,json,os,shutil,subprocess,sys,tempfile,zipfile
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'model/REF4-F-GATED-PSYCH-LATENT-ZIP-045A'
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def ignore(_d,names):return {n for n in names if n in {'data','output','__pycache__'} or n.endswith('.pyc')}
def run(source,test):
 with tempfile.TemporaryDirectory(prefix='ref4_045_verify_run_') as td:
  d=Path(td)/'b';shutil.copytree(source,d,copy_function=os.link,ignore=ignore);(d/'data').mkdir();test.to_csv(d/'data/test.csv',index=False);p=subprocess.run([sys.executable,'script.py'],cwd=d,text=True,capture_output=True,timeout=600)
  if p.returncode:raise RuntimeError({'stdout':p.stdout,'stderr':p.stderr,'code':p.returncode})
  return pd.read_csv(d/'output/submission.csv')
def main():
 c=json.loads((OUT/'audit_contract.json').read_text());res=json.loads((OUT/'result.json').read_text());man=json.loads((OUT/'audit_manifest.json').read_text());checks=[]
 def ck(n,p,a,e=None):checks.append({'name':n,'checked':True,'pass':bool(p),'actual':a,'expected':e})
 bad=[]
 for rel,v in man['artifacts'].items():
  p=ROOT/rel;actual=sha(p) if p.is_file() else None
  if actual!=v['sha256'] or (p.stat().st_size if p.is_file() else None)!=v['size']:bad.append(rel)
 ck('manifest_hash_size',not bad,bad,[]);ck('manifest_count',man['artifact_count']==len(man['artifacts']),len(man['artifacts']),man['artifact_count']);prod=json.loads((ROOT/c['production_attestation']).read_text());ck('production_binding',prod['overall_status']=='AUDIT_VERIFIED' and prod['asset_status']=='PRODUCTION_ASSETS_VERIFIED' and prod['mismatch_count']==0,{'status':prod['overall_status'],'asset_status':prod['asset_status'],'mismatch':prod['mismatch_count']});target=ROOT/c['output_zip'];cand=ROOT/c['candidate_dir'];inventory=pd.read_csv(OUT/'package_inventory.csv');zf=zipfile.ZipFile(target);names=zf.namelist();ck('zip_member_count_names',len(names)==len(set(names))==len(inventory)==res['candidate_file_count']==res['zip_member_count']==man['candidate_file_count']==man['zip_member_count'],[len(names),len(set(names)),len(inventory),res['candidate_file_count'],res['zip_member_count'],man['candidate_file_count'],man['zip_member_count']]);member_bad=[]
 for r in inventory.itertuples(index=False):
  p=cand/r.member
  if not p.is_file() or p.stat().st_size!=r.size or sha(p)!=r.sha256 or r.member not in names or hashlib.sha256(zf.read(r.member)).hexdigest()!=r.sha256:member_bad.append(r.member)
 ck('candidate_zip_member_hashes',not member_bad,member_bad,[]);ck('zip_sha',sha(target)==res['zip_sha256'],sha(target),res['zip_sha256']);ck('base_preserved',sha(ROOT/c['base_zip'])==c['preserve_zip_sha256'],sha(ROOT/c['base_zip']),c['preserve_zip_sha256']);test=pd.read_csv(ROOT/'data/test.csv');saved=pd.read_csv(OUT/'full_predictions.csv')
 with tempfile.TemporaryDirectory(prefix='ref4_045_verify_zip_') as td:
  ex=Path(td)/'bundle';zf.extractall(ex);full=run(ex,test);single=run(ex,test.iloc[[0]].copy());permt=test.sample(frac=1,random_state=45045).reset_index(drop=True);perm=run(ex,permt);extra=test.iloc[[0]].copy();extra['row_id']=extra.row_id.astype(str)+'_VERIFY_AUG';augt=pd.concat([test,extra],ignore_index=True);aug=run(ex,augt);fullp=full.set_index('row_id').control_success;saved_diff=float(np.max(np.abs(full.control_success.to_numpy()-saved.control_success.to_numpy())));single_diff=float(abs(single.control_success.iloc[0]-fullp.loc[single.row_id.iloc[0]]));perm_diff=float(np.max(np.abs(perm.set_index('row_id').loc[full.row_id].control_success.to_numpy()-full.control_success.to_numpy())));aug_diff=float(np.max(np.abs(aug.set_index('row_id').loc[full.row_id].control_success.to_numpy()-full.control_success.to_numpy())));ck('zip_full_saved',full.row_id.tolist()==test.row_id.tolist()==saved.row_id.tolist() and saved_diff<=1e-12,{'rows':len(full),'max_abs_diff':saved_diff},{'rows':len(test),'tolerance':1e-12});ck('singleton',single_diff<=1e-12,single_diff,1e-12);ck('permutation',perm_diff<=1e-12,perm_diff,1e-12);ck('augmentation',aug_diff<=1e-12,aug_diff,1e-12);p=full.control_success.to_numpy();ck('prediction_valid',np.isfinite(p).all() and ((p>=0)&(p<=1)).all(),{'min':float(p.min()),'max':float(p.max())});script=(ex/'script.py').read_text();ck('static_F_only_gate','correction = apply_linear_residual' in script and 'p = np.where(futures, p + correction, p)' in script and script.count('build_production_features')==2,{'F_gate_present':'p = np.where(futures, p + correction, p)' in script});spec=importlib.util.spec_from_file_location('packaged_psych_latent',ex/'src/psych_latent.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod);raw=pd.read_csv(ROOT/'data/train.csv',low_memory=False);probe_rows=pd.concat([raw[raw.game_type.eq('F')].tail(128),raw[raw.game_type.ne('F')].tail(128)],ignore_index=True);probe_rows['season']=2025;x=mod.build_production_features(probe_rows,ex/'model/psych_profile.pkl',ex/'model/latent_pitch_context.csv');corr=mod.apply_linear_residual(x,ex/'model/psych_latent_meta.npz');gated=np.where(probe_rows.game_type.eq('F'),corr,0.0);sp=pd.read_csv(ROOT/'model/REF4-F-GATED-PSYCH-LATENT-PRODUCTION-044A/production_probe.csv');probe_diff=max(float(np.max(np.abs(corr-sp.correction.to_numpy()))),float(np.max(np.abs(gated-sp.gated_correction.to_numpy()))));ck('packaged_F_probe_csv_roundtrip',sp.row_id.tolist()==probe_rows.row_id.tolist() and probe_diff<=1e-8,{'rows':len(sp),'F_rows':int(probe_rows.game_type.eq('F').sum()),'max_abs_diff':probe_diff},{'rows':256,'F_rows':128,'tolerance':1e-8})
 result_checks={k:bool(v) for k,v in res['checks'].items()};ck('executor_checks',all(result_checks.values()) and res['fail_count']==0 and res['pass_count']==res['checked_count']==len(result_checks),result_checks);ck('sample_limitation_recorded',res['test_game_type_counts'].get('F',0)==0, res['test_game_type_counts'],{'F':0})
 fail=[q['name'] for q in checks if not q['pass']];report={'experiment_id':c['experiment_id'],'status':'AUDIT_VERIFIED' if not fail else 'AUDIT_FAIL_REPORT','package_status':'READY_FOR_SUBMISSION' if not fail else 'HOLD','checked_count':len(checks),'pass_count':len(checks)-len(fail),'fail_count':len(fail),'mismatch_count':len(fail),'failures':fail,'checks':checks,'candidate_file_count':len(inventory),'zip_member_count':len(names),'test_rows':len(test),'test_game_type_counts':test.game_type.value_counts().to_dict(),'independent_singleton_max_abs_diff':single_diff,'independent_permutation_max_abs_diff':perm_diff,'independent_augmentation_max_abs_diff':aug_diff,'independent_zip_saved_max_abs_diff':saved_diff,'packaged_F_probe_max_abs_diff':probe_diff,'known_limitation':'local test.csv has zero F rows; packaged F path is covered by the 128-row production probe, while full server F inference remains unobserved locally'};rp=OUT/'validation_report.json';rp.write_text(json.dumps(report,ensure_ascii=False,indent=2,default=lambda v:v.item() if hasattr(v,'item') else str(v))+'\n');a={'experiment_id':c['experiment_id'],'overall_status':report['status'],'package_status':report['package_status'],'checked_count':len(checks),'pass_count':len(checks)-len(fail),'fail_count':len(fail),'mismatch_count':len(fail),'candidate_file_count':len(inventory),'zip_member_count':len(names),'test_rows':len(test),'test_F_rows':int(test.game_type.eq('F').sum()),'audit_manifest_sha256':sha(OUT/'audit_manifest.json'),'validation_report_sha256':sha(rp),'validator_sha256':sha(Path(__file__)),'result_sha256':sha(OUT/'result.json'),'package_inventory_sha256':sha(OUT/'package_inventory.csv'),'output_zip_sha256':sha(target),'base_zip_sha256':sha(ROOT/c['base_zip']),'production_attestation_sha256':sha(ROOT/c['production_attestation']),'training_performed':False,'test_read':True,'test_inference_performed':True,'candidate_bundle_created':True,'zip_created':True,'submission_performed':False};(OUT/'audit_attestation.json').write_text(json.dumps(a,indent=2)+'\n');print(json.dumps({k:a[k] for k in ('overall_status','package_status','checked_count','pass_count','fail_count','mismatch_count','candidate_file_count','zip_member_count','test_rows','test_F_rows','output_zip_sha256')},indent=2));
 if fail:raise SystemExit(2)
if __name__=='__main__':main()
