#!/usr/bin/env python3
import hashlib,importlib.util,json,pickle
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'model/REF4-F-GATED-PSYCH-LATENT-PRODUCTION-044A';CONDS=('high_li','extreme_li','traffic','risp','late','close','behind','three_ball','two_strike','full_count','compound_pressure')
spec=importlib.util.spec_from_file_location('independent_features',ROOT/'scripts/verify_ref4_trainonly_psych_latent_042a.py');vf=importlib.util.module_from_spec(spec);spec.loader.exec_module(vf)
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def independent_bundle(history,a):
 h=history.reset_index(drop=True);flags=vf.flags(h);y=h.control_success.astype(float);ids=h.pitcher_id.astype(str);g=float(y.mean());agg=pd.DataFrame({'id':ids,'y':y}).groupby('id',sort=False).y.agg(['sum','count']);overall=(agg['sum']+a*g)/(agg['count']+a);profile=pd.DataFrame({'psych_history_log_n':np.log1p(agg['count'])},index=agg.index);league={}
 for name in CONDS:
  mask=flags[name].astype(bool);league[name]=float(y[mask].mean())-g if mask.any() else 0.0;part=pd.DataFrame({'id':ids[mask],'y':y[mask]}).groupby('id',sort=False).y.agg(['sum','count']);s=part['sum'].reindex(profile.index).fillna(0);n=part['count'].reindex(profile.index).fillna(0);rate=(s+a*overall)/(n+a);profile[f'psych_{name}_effect']=rate-overall;profile[f'psych_{name}_reliability']=n/(n+a)
 return {'profile':profile.reset_index(names='pitcher_id'),'league':league}
def main():
 c=json.loads((OUT/'audit_contract.json').read_text());fit=json.loads((OUT/'production_fit.json').read_text());man=json.loads((OUT/'audit_manifest.json').read_text());checks=[]
 def ck(n,p,a,e=None):checks.append({'name':n,'checked':True,'pass':bool(p),'actual':a,'expected':e})
 bad=[]
 for rel,v in man['artifacts'].items():
  p=ROOT/rel;actual=sha(p) if p.is_file() else None
  if actual!=v['sha256'] or (p.stat().st_size if p.is_file() else None)!=v['size']:bad.append(rel)
 ck('manifest_hash_size',not bad,bad,[]);ck('manifest_count',man['artifact_count']==len(man['artifacts']),len(man['artifacts']),man['artifact_count']);prom=json.loads((ROOT/c['promotion_attestation']).read_text());ck('promotion_binding',prom['overall_status']=='AUDIT_VERIFIED' and prom['performance_status']=='PASS' and prom['promotion_pass'] is True and prom['mismatch_count']==0,{'status':prom['overall_status'],'performance':prom['performance_status'],'pass':prom['promotion_pass'],'mismatch':prom['mismatch_count']});cfg=c['fixed_fit'];raw=pd.read_csv(ROOT/'data/train.csv',low_memory=False);tm=pd.read_csv(ROOT/'data/trackman_history.csv',usecols=['pitcher_trackman_id','season','balls_before','strikes_before','batter_hand','pitch_type_group']);lookup=raw.set_index('row_id',drop=False);xs=[];targets=[];weights=[]
 for key in ('2022','2023','2024'):
  year=int(key);o=pd.read_csv(ROOT/c['oof_sources'][key]);rows=lookup.loc[o.row_id].reset_index(drop=True);mp=pd.read_csv(ROOT/c['fold_mapping'][key]);table=vf.pitch_table(year,mp,tm,float(cfg['latent_parent_strength']),float(cfg['latent_context_strength']));x=pd.concat([vf.profile_x(rows,raw[raw.season.lt(year)],float(cfg['psych_shrinkage_alpha'])),vf.pitch_x(rows,table)],axis=1);xs.append(x);targets.append(o.target.to_numpy(float)-o.prediction.to_numpy(float));weights.append(np.full(len(o),float(cfg['season_weights'][key])));source=fit['source_folds'][['2022','2023','2024'].index(key)];ck('source_'+key,len(o)==source['rows'] and len(x.columns)==source['feature_count'] and len(mp)==source['mapping_rows'] and len(table)==source['latent_rows'] and int(tm[tm.season.lt(year)].season.max())==source['trackman_max_season'],{'rows':len(o),'features':len(x.columns),'mapping':len(mp),'latent':len(table),'tm_max':int(tm[tm.season.lt(year)].season.max())},source)
 x=pd.concat(xs,ignore_index=True);target=np.concatenate(targets);w=np.concatenate(weights);mean=x.mean();std=x.std().replace(0,1).fillna(1);z=((x-mean)/std).fillna(0);ridge=Ridge(alpha=float(cfg['ridge_alpha']),fit_intercept=False).fit(z,target,sample_weight=w);meta=np.load(OUT/'psych_latent_meta.npz',allow_pickle=False);ck('meta_columns',meta['columns'].tolist()==x.columns.tolist(),len(meta['columns']),len(x.columns));meta_diff=max(float(np.max(np.abs(meta['mean']-mean.to_numpy()))),float(np.max(np.abs(meta['std']-std.to_numpy()))),float(np.max(np.abs(meta['coef']-ridge.coef_))),abs(float(meta['scale'])-float(cfg['correction_scale'])),abs(float(meta['ridge_alpha'])-float(cfg['ridge_alpha'])));ck('meta_values',meta_diff<=1e-12,meta_diff,1e-12);ck('fit_counts',fit['fit_rows']==man['fit_rows']==len(x) and fit['feature_count']==man['feature_count']==len(x.columns),[fit['fit_rows'],man['fit_rows'],len(x),fit['feature_count'],man['feature_count'],len(x.columns)])
 expected_bundle=independent_bundle(raw,float(cfg['psych_shrinkage_alpha']));saved_bundle=pickle.load(open(OUT/'psych_profile.pkl','rb'));sp=saved_bundle['profile'];ep=expected_bundle['profile'];key_ok=sp.pitcher_id.astype(str).tolist()==ep.pitcher_id.astype(str).tolist() and sp.columns.tolist()==ep.columns.tolist();numcols=[q for q in sp.columns if q!='pitcher_id'];profile_diff=float(np.nanmax(np.abs(sp[numcols].to_numpy(float)-ep[numcols].to_numpy(float))));league_diff=max(abs(saved_bundle['league'][q]-expected_bundle['league'][q]) for q in CONDS);ck('profile_asset',key_ok and profile_diff<=1e-15 and league_diff<=1e-15,{'rows':len(sp),'max_abs_diff':profile_diff,'league_max_abs_diff':league_diff},{'rows':len(ep),'tolerance':1e-15})
 prodmap=pd.read_csv(ROOT/c['production_mapping']);expected_latent=vf.pitch_table(2025,prodmap,tm,float(cfg['latent_parent_strength']),float(cfg['latent_context_strength']));expected_latent.insert(1,'season',2025);saved_latent=pd.read_csv(OUT/'latent_pitch_context.csv',dtype={'pitcher_id':str,'batter_hand':str});expected_latent.pitcher_id=expected_latent.pitcher_id.astype(str);keys=['pitcher_id','season','balls_before','strikes_before','batter_hand'];latent_keys=saved_latent[keys].astype(str).equals(expected_latent[keys].astype(str));num=[q for q in saved_latent.columns if q not in keys];latent_diff=float(np.nanmax(np.abs(saved_latent[num].to_numpy(float)-expected_latent[num].to_numpy(float))));nan_same=bool(np.array_equal(np.isnan(saved_latent[num].to_numpy(float)),np.isnan(expected_latent[num].to_numpy(float))));ck('latent_asset',latent_keys and nan_same and latent_diff<=1e-14,{'rows':len(saved_latent),'max_abs_diff':latent_diff,'nan_mask_equal':nan_same},{'rows':len(expected_latent),'tolerance':1e-14})
 probe_rows=pd.concat([raw[raw.game_type.eq('F')].tail(128),raw[raw.game_type.ne('F')].tail(128)],ignore_index=True);probe_rows['season']=2025;px=pd.concat([vf.profile_x(probe_rows,raw,float(cfg['psych_shrinkage_alpha'])),vf.pitch_x(probe_rows,expected_latent.drop(columns='season'))],axis=1);corr=((px[x.columns]-mean)/std).fillna(0).to_numpy()@ridge.coef_*float(cfg['correction_scale']);gated=np.where(probe_rows.game_type.eq('F'),corr,0.0);saved_probe=pd.read_csv(OUT/'production_probe.csv');probe_diff=max(float(np.max(np.abs(saved_probe.correction.to_numpy()-corr))),float(np.max(np.abs(saved_probe.gated_correction.to_numpy()-gated))));ck('production_probe',saved_probe.row_id.tolist()==probe_rows.row_id.tolist() and probe_diff<=1e-15,{'rows':len(saved_probe),'max_abs_diff':probe_diff},{'rows':len(probe_rows),'tolerance':1e-15});ck('required_assets',all((OUT/p).is_file() for p in c['required_assets']),[p for p in c['required_assets'] if not (OUT/p).is_file()],[]);ck('no_test_candidate_zip',fit['test_read'] is False and fit['test_inference_performed'] is False and fit['candidate_bundle_created'] is False and fit['zip_created'] is False,{k:fit[k] for k in ('test_read','test_inference_performed','candidate_bundle_created','zip_created')})
 fail=[q['name'] for q in checks if not q['pass']];report={'experiment_id':c['experiment_id'],'status':'AUDIT_VERIFIED' if not fail else 'AUDIT_FAIL_REPORT','asset_status':'PRODUCTION_ASSETS_VERIFIED' if not fail else 'HOLD','checked_count':len(checks),'pass_count':len(checks)-len(fail),'fail_count':len(fail),'mismatch_count':len(fail),'failures':fail,'checks':checks,'fit_rows':len(x),'feature_count':len(x.columns),'profile_rows':len(ep),'latent_rows':len(expected_latent),'probe_rows':len(probe_rows)};rp=OUT/'validation_report.json';rp.write_text(json.dumps(report,ensure_ascii=False,indent=2,default=lambda v:v.item() if hasattr(v,'item') else str(v))+'\n');a={'experiment_id':c['experiment_id'],'overall_status':report['status'],'asset_status':report['asset_status'],'checked_count':len(checks),'pass_count':len(checks)-len(fail),'fail_count':len(fail),'mismatch_count':len(fail),'asset_count':len(c['required_assets']),'fit_rows':len(x),'feature_count':len(x.columns),'profile_rows':len(ep),'latent_rows':len(expected_latent),'probe_rows':len(probe_rows),'audit_manifest_sha256':sha(OUT/'audit_manifest.json'),'validation_report_sha256':sha(rp),'validator_sha256':sha(Path(__file__)),'production_fit_sha256':sha(OUT/'production_fit.json'),'psych_profile_sha256':sha(OUT/'psych_profile.pkl'),'latent_pitch_context_sha256':sha(OUT/'latent_pitch_context.csv'),'psych_latent_meta_sha256':sha(OUT/'psych_latent_meta.npz'),'production_probe_sha256':sha(OUT/'production_probe.csv'),'preserved_zip_sha256':sha(ROOT/c['preserve_zip']),'training_performed':True,'test_read':False,'test_inference_performed':False,'candidate_bundle_created':False,'zip_created':False};(OUT/'audit_attestation.json').write_text(json.dumps(a,indent=2)+'\n');print(json.dumps({k:a[k] for k in ('overall_status','asset_status','checked_count','pass_count','fail_count','mismatch_count','fit_rows','feature_count','profile_rows','latent_rows','probe_rows')},indent=2));
 if fail:raise SystemExit(2)
if __name__=='__main__':main()
