#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'model/REF4-TRAINONLY-F-GATED-PSYCH-LATENT-043A'
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for q in iter(lambda:f.read(1<<20),b''):h.update(q)
 return h.hexdigest()
def ci(y,b,p,g,reps,seed):
 delta=(b-y)**2-(p-y)**2;codes,u=pd.factorize(g,sort=True);s=np.bincount(codes,weights=delta,minlength=len(u));n=np.bincount(codes,minlength=len(u));rng=np.random.default_rng(seed);draw=np.empty(reps)
 for i in range(reps):
  ids=rng.integers(0,len(u),len(u));draw[i]=s[ids].sum()/n[ids].sum()
 return float(delta.mean()),float(np.quantile(draw,.025)),float(np.quantile(draw,.975)),len(u)
def main():
 c=json.loads((OUT/'audit_contract.json').read_text());res=json.loads((OUT/'result.json').read_text());man=json.loads((OUT/'audit_manifest.json').read_text());checks=[]
 def ck(n,p,a,e=None):checks.append({'name':n,'checked':True,'pass':bool(p),'actual':a,'expected':e})
 bad=[]
 for rel,v in man['artifacts'].items():
  p=ROOT/rel;actual=sha(p) if p.is_file() else None
  if actual!=v['sha256'] or (p.stat().st_size if p.is_file() else None)!=v['size']:bad.append(rel)
 ck('manifest',not bad,bad,[]);ck('manifest_count',man['artifact_count']==len(man['artifacts']),len(man['artifacts']),man['artifact_count']);att=json.loads((ROOT/c['upstream_attestation']).read_text());ck('upstream_binding',att['overall_status']=='AUDIT_VERIFIED' and att['mismatch_count']==0 and att['oof_predictions_sha256']==sha(ROOT/c['upstream_predictions']),{'status':att['overall_status'],'mismatch_count':att['mismatch_count'],'hash_match':att['oof_predictions_sha256']==sha(ROOT/c['upstream_predictions'])});up=pd.read_csv(ROOT/c['upstream_predictions']);raw=pd.read_csv(ROOT/'data/train.csv',usecols=['row_id','game_type']);d=up.merge(raw,on='row_id',validate='one_to_one');expected=np.where(d.game_type.eq(c['row_local_gate']['apply_value']),d.candidate_prediction,d.baseline_prediction);saved=pd.read_csv(OUT/'oof_predictions.csv');diff=float(np.max(np.abs(saved.gated_prediction.to_numpy()-expected)));ck('row_ids_predictions',saved.row_id.tolist()==d.row_id.tolist() and diff<=1e-15,{'rows':len(saved),'max_abs_diff':diff},{'rows':len(d),'max_abs_diff':1e-15});fold={}
 for y,z in d.assign(gated=expected).groupby('season'):
  t=z.target.to_numpy(float);b=z.baseline_prediction.to_numpy(float);p=z.gated.to_numpy(float);v=ci(t,b,p,z.pitcher_id.to_numpy(),int(c['promotion_gate']['cluster_bootstrap_repetitions']),int(c['promotion_gate']['cluster_bootstrap_seed_'+str(y)]));ref=float(np.mean((t-t.mean())**2));bss=(1-np.mean((p-t)**2)/ref)-(1-np.mean((b-t)**2)/ref);r=res['folds'][str(y)];ck('metrics_'+str(y),max(abs(v[0]-r['brier_gain']),abs(v[1]-r['cluster_ci']['ci_low']),abs(v[2]-r['cluster_ci']['ci_high']),abs(bss-r['bss_gain']))<=1e-15,{'gain':v[0],'ci':v[1:3],'bss_gain':bss},{'gain':r['brier_gain'],'ci':[r['cluster_ci']['ci_low'],r['cluster_ci']['ci_high']],'bss_gain':r['bss_gain']});fold[str(y)]={'gain':v[0],'ci_low':v[1],'bss_gain':bss}
 t=d.target.to_numpy(float);b=d.baseline_prediction.to_numpy(float);pg=float(np.mean((b-t)**2)-np.mean((expected-t)**2));gate={'2023_brier_gain':fold['2023']['gain']>0,'2024_brier_gain':fold['2024']['gain']>0,'pooled_brier_gain':pg>0,'worst_season_bss_gain':min(v['bss_gain'] for v in fold.values())>0,'2023_cluster_ci_low':fold['2023']['ci_low']>0,'2024_cluster_ci_low':fold['2024']['ci_low']>0};passed=all(gate.values());ck('pooled',abs(pg-res['pooled']['brier_gain'])<=1e-15,pg,res['pooled']['brier_gain']);ck('gate',gate==res['gate_checks'],res['gate_checks'],gate);ck('counts',res['actual_leaf_count']==man['leaf_count']==1 and res['gate_checks_count']==man['gate_count']==len(gate),[res['actual_leaf_count'],man['leaf_count'],res['gate_checks_count'],man['gate_count'],len(gate)]);ck('promotion',res['promotion_pass'] is passed,res['promotion_pass'],passed);ck('no_mutation',not any(res[k] for k in ('training_performed','test_read','test_inference_performed','production_assets_created','candidate_bundle_created','zip_created')),{k:res[k] for k in ('training_performed','test_read','test_inference_performed','production_assets_created','candidate_bundle_created','zip_created')});md=(OUT/'result.md').read_text();ck('markdown',res['candidate_name'] in md and res['candidate_status'] in md and f'`{str(passed).lower()}`' in md,res['candidate_name']);fail=[x['name'] for x in checks if not x['pass']];report={'experiment_id':c['experiment_id'],'status':'AUDIT_VERIFIED' if not fail else 'AUDIT_FAIL_REPORT','checked_count':len(checks),'pass_count':len(checks)-len(fail),'fail_count':len(fail),'mismatch_count':len(fail),'failures':fail,'checks':checks,'recomputed_folds':fold,'pooled_brier_gain':pg,'expected_gate':gate,'promotion_pass':passed};rp=OUT/'validation_report.json';rp.write_text(json.dumps(report,ensure_ascii=False,indent=2,default=lambda v:v.item() if hasattr(v,'item') else str(v))+'\n');a={'experiment_id':c['experiment_id'],'overall_status':report['status'],'performance_status':'PASS' if passed else 'FAIL','candidate_count':1,'leaf_count':1,'gate_count':len(gate),'checked_count':len(checks),'pass_count':len(checks)-len(fail),'fail_count':len(fail),'mismatch_count':len(fail),'audit_manifest_sha256':sha(OUT/'audit_manifest.json'),'validation_report_sha256':sha(rp),'validator_sha256':sha(Path(__file__)),'result_sha256':sha(OUT/'result.json'),'oof_predictions_sha256':sha(OUT/'oof_predictions.csv'),'upstream_predictions_sha256':sha(ROOT/c['upstream_predictions']),'preserved_zip_sha256':sha(ROOT/c['preserve_zip']),'promotion_pass':passed,'training_performed':False,'test_read':False,'test_inference_performed':False,'production_assets_created':False,'candidate_bundle_created':False,'zip_created':False};(OUT/'audit_attestation.json').write_text(json.dumps(a,indent=2)+'\n');print(json.dumps({k:a[k] for k in ('overall_status','performance_status','checked_count','pass_count','fail_count','mismatch_count','promotion_pass')},indent=2));
 if fail:raise SystemExit(2)
if __name__=='__main__':main()
