#!/usr/bin/env python3
"""Independent raw-source verifier for 042A."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'model/REF4-TRAINONLY-PSYCH-LATENT-042A'
C=('high_li','extreme_li','traffic','risp','late','close','behind','three_ball','two_strike','full_count','compound_pressure');G=('fastball','breaking','offspeed','other')
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for q in iter(lambda:f.read(1<<20),b''):h.update(q)
 return h.hexdigest()
def flags(d):
 n=lambda x:pd.to_numeric(d[x],errors='coerce').fillna(0);li=n('li');inn=n('inning');score=n('score_diff_pitcher_team');balls=n('balls_before');strikes=n('strikes_before');runners=n('num_runners_on');risp=d.runner_on_2b.fillna(0).ne(0)|d.runner_on_3b.fillna(0).ne(0)
 vals=[li.ge(1.5),li.ge(3),runners.gt(0),risp,inn.ge(7),score.abs().le(1),score.lt(0),balls.eq(3),strikes.eq(2),balls.eq(3)&strikes.eq(2),li.ge(1.5)&(risp|balls.eq(3))&score.abs().le(2)]
 return pd.DataFrame(dict(zip(C,vals)),index=d.index).astype('int8')
def profile_x(rows,hist,a):
 h=hist.reset_index(drop=True);f=flags(h);target=h.control_success.astype(float);ids=h.pitcher_id.astype(str);global_rate=float(target.mean());agg=pd.DataFrame({'id':ids,'y':target}).groupby('id',sort=False).y.agg(['sum','count']);overall=(agg['sum']+a*global_rate)/(agg['count']+a);prof=pd.DataFrame({'psych_history_log_n':np.log1p(agg['count'])},index=agg.index);defaults={}
 for name in C:
  mask=f[name].astype(bool);defaults[name]=float(target[mask].mean())-global_rate if mask.any() else 0.0;part=pd.DataFrame({'id':ids[mask],'y':target[mask]}).groupby('id',sort=False).y.agg(['sum','count']);s=part['sum'].reindex(prof.index).fillna(0);n=part['count'].reindex(prof.index).fillna(0);rate=(s+a*overall)/(n+a);prof[f'psych_{name}_effect']=rate-overall;prof[f'psych_{name}_reliability']=n/(n+a)
 out=pd.DataFrame({'pitcher_id':rows.pitcher_id.astype(str).array}).merge(prof.reset_index(names='pitcher_id'),on='pitcher_id',how='left',sort=False).drop(columns='pitcher_id');out.psych_history_log_n=out.psych_history_log_n.fillna(0);rf=flags(rows.reset_index(drop=True))
 for name in C:
  effect=out[f'psych_{name}_effect'].fillna(defaults[name]);reliability=out[f'psych_{name}_reliability'].fillna(0);active=rf[name].astype(float).to_numpy();out[f'psych_{name}_active_effect']=effect*active;out[f'psych_{name}_active_reliability']=reliability*active;out[f'psych_{name}_effect']=effect;out[f'psych_{name}_reliability']=reliability
 return out.astype('float32')
def pitch_table(year,mapdf,tm,parent,context):
 mp=mapdf.copy();mp.pitcher_id=mp.pitcher_id.astype(str);h=tm[tm.season.lt(year)].merge(mp[['pitcher_id','pitcher_trackman_id','mapping_similarity']],on='pitcher_trackman_id',how='inner');h.pitcher_id=h.pitcher_id.astype(str);h.batter_hand=h.batter_hand.astype(str);base=pd.crosstab(h.pitcher_id,h.pitch_type_group).reindex(columns=G,fill_value=0);prior=(base+parent*np.array([.5,.3,.15,.05]))/(base.sum(1).to_numpy()[:,None]+parent);idxcols=['pitcher_id','balls_before','strikes_before','batter_hand'];wide=h.groupby(idxcols+['pitch_type_group']).size().unstack(fill_value=0).reindex(columns=G,fill_value=0);ix=wide.index;n=wide.sum(1).to_numpy();par=prior.reindex(ix.get_level_values('pitcher_id')).to_numpy();prob=(wide.to_numpy()+context*par)/(n[:,None]+context);t=ix.to_frame(index=False);t['latent_pitch_n']=n;t['latent_mapping_similarity']=mp.set_index('pitcher_id').mapping_similarity.reindex(t.pitcher_id).to_numpy()
 for j,name in enumerate(G):t[f'latent_{name}_prob']=prob[:,j]
 return t
def pitch_x(rows,t):
 hand=rows.batter_hand.map({1:'Left',2:'Right'}).fillna(rows.batter_hand.astype(str));keys=pd.DataFrame({'pitcher_id':rows.pitcher_id.astype(str),'balls_before':rows.balls_before.astype(int),'strikes_before':rows.strikes_before.astype(int),'batter_hand':hand});z=keys.merge(t,on=['pitcher_id','balls_before','strikes_before','batter_hand'],how='left',sort=False).drop(columns=['pitcher_id','balls_before','strikes_before','batter_hand']);n=pd.to_numeric(z.latent_pitch_n,errors='coerce').fillna(0);z['latent_log_n']=np.log1p(n);z['latent_reliability']=n/(n+100);p=z[[f'latent_{x}_prob' for x in G]].clip(1e-6,1);z['latent_entropy']=-(p*np.log(p)).sum(axis=1);z['latent_fast_vs_break']=p.latent_fastball_prob-p.latent_breaking_prob;return z.replace([np.inf,-np.inf],np.nan)
def bootstrap(y,b,p,groups,reps,seed):
 delta=(b-y)**2-(p-y)**2;codes,unique=pd.factorize(groups,sort=True);s=np.bincount(codes,weights=delta,minlength=len(unique));n=np.bincount(codes,minlength=len(unique));rng=np.random.default_rng(seed);draw=[]
 for _ in range(reps):
  ids=rng.integers(len(unique),size=len(unique));draw.append(s[ids].sum()/n[ids].sum())
 return float(delta.mean()),float(np.quantile(draw,.025)),float(np.quantile(draw,.975)),len(unique)
def main():
 c=json.loads((OUT/'audit_contract.json').read_text());res=json.loads((OUT/'result.json').read_text());man=json.loads((OUT/'audit_manifest.json').read_text());checks=[]
 def ck(name,ok,actual,expected=None):checks.append({'name':name,'checked':True,'pass':bool(ok),'actual':actual,'expected':expected})
 bad=[]
 for rel,v in man['artifacts'].items():
  p=ROOT/rel;actual=sha(p) if p.is_file() else None
  if actual!=v['sha256'] or (p.stat().st_size if p.is_file() else None)!=v['size']:bad.append(rel)
 ck('manifest_hash_size',not bad,bad,[]);ck('manifest_count',man['artifact_count']==len(man['artifacts']),len(man['artifacts']),man['artifact_count'])
 raw=pd.read_csv(ROOT/'data/train.csv',low_memory=False);tm=pd.read_csv(ROOT/'data/trackman_history.csv',usecols=['pitcher_trackman_id','season','balls_before','strikes_before','batter_hand','pitch_type_group']);lookup=raw.set_index('row_id',drop=False);frames={};x={};cfg=c['fixed_candidate']
 for ys,rel in c['base_oof'].items():
  year=int(ys);o=pd.read_csv(ROOT/rel);rows=lookup.loc[o.row_id].reset_index(drop=True);mp=pd.read_csv(ROOT/c['fold_mapping'][ys]);table=pitch_table(year,mp,tm,float(cfg['latent_parent_strength']),float(cfg['latent_context_strength']));feat=pd.concat([profile_x(rows,raw[raw.season.lt(year)],float(cfg['psych_shrinkage_alpha'])),pitch_x(rows,table)],axis=1);frames[year]=(o,rows);x[year]=feat;source=res['source_audits'][[z['season'] for z in res['source_audits']].index(year)];ck(f'source_rows_{year}',len(rows)==source['rows']==len(feat),[len(rows),len(feat)],source['rows']);ck(f'source_cutoffs_{year}',int(raw[raw.season.lt(year)].season.max())==source['history_max_season'] and int(tm[tm.season.lt(year)].season.max())==source['trackman_max_season'],[int(raw[raw.season.lt(year)].season.max()),int(tm[tm.season.lt(year)].season.max())],[source['history_max_season'],source['trackman_max_season']]);ck(f'features_{year}',feat.columns.tolist()==source['feature_names'] and len(feat.columns)==source['feature_count'],{'count':len(feat.columns)}, {'count':source['feature_count']})
 saved=pd.read_csv(OUT/'oof_predictions.csv');parts=[];foldvals={}
 for protocol in c['temporal_protocol']:
  vy=int(protocol['validation_season']);years=[int(v) for v in protocol['fit_seasons']];train=pd.concat([x[v] for v in years],ignore_index=True);mu=train.mean();sd=train.std().replace(0,1).fillna(1);z=((train-mu)/sd).fillna(0);zv=((x[vy]-mu)/sd).fillna(0);target_train=np.concatenate([frames[v][0].target.to_numpy(float)-frames[v][0].prediction.to_numpy(float) for v in years]);weights=np.concatenate([np.full(len(frames[v][0]),float(cfg['recent_year_weight']) if v==max(years) else float(cfg['older_year_weight'])) for v in years]);model=Ridge(alpha=float(cfg['ridge_alpha']),fit_intercept=False).fit(z,target_train,sample_weight=weights);o,rows=frames[vy];y=o.target.to_numpy(float);b=o.prediction.to_numpy(float);p=np.clip(b+float(cfg['correction_scale'])*model.predict(zv),1e-5,1-1e-5);record=saved[saved.season.eq(vy)];diff=float(np.max(np.abs(record.candidate_prediction.to_numpy(float)-p)));ck(f'prediction_{vy}',record.row_id.tolist()==o.row_id.tolist() and diff<=1e-15,{'rows':len(record),'max_abs_diff':diff},{'rows':len(o),'max_abs_diff':1e-15});bg=float(np.mean((b-y)**2)-np.mean((p-y)**2));ref=float(np.mean((y-y.mean())**2));bss=(1-np.mean((p-y)**2)/ref)-(1-np.mean((b-y)**2)/ref);ci=bootstrap(y,b,p,rows.pitcher_id.to_numpy(),int(c['promotion_gate']['cluster_bootstrap_repetitions']),int(c['promotion_gate']['cluster_bootstrap_seed_'+str(vy)]));r=res['folds'][str(vy)];ck(f'metrics_{vy}',max(abs(bg-r['brier_gain']),abs(bss-r['bss_gain']),abs(ci[0]-r['cluster_ci']['brier_gain']),abs(ci[1]-r['cluster_ci']['ci_low']),abs(ci[2]-r['cluster_ci']['ci_high']))<=1e-15,{'brier_gain':bg,'bss_gain':bss,'ci':ci[:3]},{'brier_gain':r['brier_gain'],'bss_gain':r['bss_gain'],'ci':[r['cluster_ci'][k] for k in ('brier_gain','ci_low','ci_high')]});foldvals[str(vy)]={'gain':bg,'bss_gain':bss,'ci_low':ci[1]};parts.append((y,b,p))
 y=np.concatenate([q[0] for q in parts]);b=np.concatenate([q[1] for q in parts]);p=np.concatenate([q[2] for q in parts]);pooled=float(np.mean((b-y)**2)-np.mean((p-y)**2));gate={'2023_brier_gain':foldvals['2023']['gain']>0,'2024_brier_gain':foldvals['2024']['gain']>0,'pooled_brier_gain':pooled>0,'worst_season_bss_gain':min(v['bss_gain'] for v in foldvals.values())>0,'2023_cluster_ci_low':foldvals['2023']['ci_low']>0,'2024_cluster_ci_low':foldvals['2024']['ci_low']>0};expected=all(gate.values());ck('pooled_gain',abs(pooled-res['pooled']['brier_gain'])<=1e-15,pooled,res['pooled']['brier_gain']);ck('gate_fields',gate==res['gate_checks'],res['gate_checks'],gate);ck('counts',res['actual_leaf_count']==man['leaf_count']==1 and res['gate_checks_count']==man['gate_count']==len(gate),[res['actual_leaf_count'],man['leaf_count'],res['gate_checks_count'],man['gate_count'],len(gate)]);ck('promotion',res['promotion_pass'] is expected,res['promotion_pass'],expected);ck('no_forbidden_outputs',not any(res[k] for k in ('test_read','test_inference_performed','production_assets_created','candidate_bundle_created','zip_created')),{k:res[k] for k in ('test_read','test_inference_performed','production_assets_created','candidate_bundle_created','zip_created')});md=(OUT/'result.md').read_text();ck('markdown',res['candidate_name'] in md and res['candidate_status'] in md and f'`{str(expected).lower()}`' in md,res['candidate_name'])
 failures=[q['name'] for q in checks if not q['pass']];report={'experiment_id':c['experiment_id'],'status':'AUDIT_VERIFIED' if not failures else 'AUDIT_FAIL_REPORT','checked_count':len(checks),'pass_count':len(checks)-len(failures),'fail_count':len(failures),'mismatch_count':len(failures),'failures':failures,'checks':checks,'recomputed_folds':foldvals,'pooled_brier_gain':pooled,'expected_gate':gate,'promotion_pass':expected};rp=OUT/'validation_report.json';rp.write_text(json.dumps(report,ensure_ascii=False,indent=2,default=lambda v:v.item() if hasattr(v,'item') else str(v))+'\n');att={'experiment_id':c['experiment_id'],'overall_status':report['status'],'performance_status':'PASS' if expected else 'FAIL','candidate_count':1,'leaf_count':1,'gate_count':len(gate),'checked_count':len(checks),'pass_count':len(checks)-len(failures),'fail_count':len(failures),'mismatch_count':len(failures),'audit_manifest_sha256':sha(OUT/'audit_manifest.json'),'validation_report_sha256':sha(rp),'validator_sha256':sha(Path(__file__)),'result_sha256':sha(OUT/'result.json'),'oof_predictions_sha256':sha(OUT/'oof_predictions.csv'),'preserved_zip_sha256':sha(ROOT/c['preserve_zip']),'promotion_pass':expected,'test_read':False,'test_inference_performed':False,'production_assets_created':False,'candidate_bundle_created':False,'zip_created':False};(OUT/'audit_attestation.json').write_text(json.dumps(att,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:att[k] for k in ('overall_status','performance_status','checked_count','pass_count','fail_count','mismatch_count','promotion_pass')},indent=2));
 if failures:raise SystemExit(2)
if __name__=='__main__':main()
